# Generated by Django 4.1 on 2022-08-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordsheet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
