# Generated by Django 4.1 on 2022-08-09 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordsheet', '0004_alter_students_student_id_alter_subjects_sub_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=False, serialize=False, to='recordsheet.students')),
                ('ca', models.IntegerField()),
                ('exam', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('date_added', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
            ],
        ),
    ]
