# Generated by Django 4.1 on 2022-08-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordsheet', '0006_grade_id_alter_grade_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='date_updated',
        ),
    ]
