# Generated by Django 4.1 on 2022-08-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordsheet', '0007_remove_grade_date_added_remove_grade_date_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
