# Generated by Django 4.1 on 2022-08-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordsheet', '0009_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='student_id',
            new_name='student',
        ),
    ]
